import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../styles/globals.scss";
import Header from "@/components/ui/Header";
import {Auth} from "@/components/features/Auth";

const inter = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata: Metadata = {
  title: {
    default: "Next App",
    template: "%s | Next App",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
   news
}: Readonly<{
  children: React.ReactNode;
  news: React.ReactNode
}>) {
  return (
    <html lang="en">
      
      <body className={inter.className}>

        <Header />
        
        <main className="p-4">
         
          <div className="container mx-auto px-5">

            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
